export const GET_NOW_PLAYING_MOVIES_SUCCESS = 'GET_NOW_PLAYING_MOVIES_SUCCESS';
export const GET_POPULAR_MOVIES_SUCCESS = 'GET_POPULAR_MOVIES_SUCCESS';
export const GET_TOP_RATED_MOVIES_SUCCESS = 'GET_TOP_RATED_MOVIES_SUCCESS';
export const GET_UPCOMING_MOVIES_SUCCESS = 'GET_UPCOMING_MOVIES_SUCCESS';

// export const GET_MOVIE_DETAILS_SUCCESS = 'GET_MOVIE_DETAILS_SUCCESS';
// export const GET_MOVIES_LIST_SUCCESS = 'GET_MOVIES_LIST_SUCCESS';
// export const GET_MOVIES_GENRES_SUCCESS = 'GET_MOVIES_GENRES_SUCCESS';
// export const GET_MOVIES_SEARCH_RESULT_SUCCESS = 'GET_MOVIES_SEARCH_RESULT_SUCCESS';
